# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to=b'', validators=[image.models.validate_dataImg]),
        ),
    ]
